name: Binary tree build

on:
  push:
    branches:
        - develop
  workflow_dispatch:
    inputs:
      N:
        description: 'Value for N'
        required: false
        default: ''
      MAX_VALUE:
        description: 'Value for MAX_VALUE'
        required: false
        default: ''

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run
      run: |
        if [ -z "${{ github.event.inputs.N }}" ]; then
         export $(cat .env | xargs)
        else
         export N=${{ github.event.inputs.N }}
         export MAX_VALUE=${{ github.event.inputs.MAX_VALUE }}
        fi
        cargo run