name: Binary tree build

on:
  push:
    branches:
        - develop
  workflow_dispatch:
    inputs:
      N:
        description: 'Value for N'
        required: true
        default: '100000'
      MAX_VALUE:
        description: 'Value for MAX_VALUE'
        required: true
        default: '100000000'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run
      run: |
        export N=${{ github.event.inputs.N }}
        export MAX_VALUE=${{ github.event.inputs.MAX_VALUE }}
        cargo run